#ifndef LLVM_CLANG_TOOLS_EXTRA_CLANG_YALLA_WRAPPERS_H
#define LLVM_CLANG_TOOLS_EXTRA_CLANG_YALLA_WRAPPERS_H

#include <fstream>
#include <string>
#include <unordered_map>
#include <vector>

#include "ClangYallaUtilities.h"

void WriteWrappersFile(
    const std::string &FileName, const std::vector<std::string> &FilesToInclude,
    const std::unordered_map<std::string, WrapperInfo> &FunctionWrappers) {
  std::ofstream WrappersFile(FileName);
  WrappersFile << "// AUTOMATICALLY GENERATED BY clang-yalla\n";

  for (const std::string &IncludedFile : FilesToInclude)
    WrappersFile << "#include \"" << IncludedFile << "\"\n";

  for (const auto &[WrapperName, WI] : FunctionWrappers)
    WrappersFile << WI.WrapperDefinition << '\n';
}

#endif