#ifndef LLVM_CLANG_TOOLS_EXTRA_CLANG_YALLA_WRAPPERS_H
#define LLVM_CLANG_TOOLS_EXTRA_CLANG_YALLA_WRAPPERS_H

#include <fstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "ClangYallaUtilities.h"

void WriteWrappersFile(
    const std::string &FileName,
    const std::vector<std::pair<std::string, bool>> &FilesToInclude,
    const std::unordered_set<std::string> &FunctionWrappers,
    const std::unordered_set<std::string> &ClassTemplateInstantiations,
    const std::unordered_set<std::string> &FunctionTemplateInstantiations) {
  std::ofstream WrappersFile(FileName);
  WrappersFile << "// AUTOMATICALLY GENERATED BY clang-yalla\n";

  for (const auto &[IncludedFile, IsAngled] : FilesToInclude) {
    std::string Prefix = IsAngled ? "<" : "\"";
    std::string Suffix = IsAngled ? ">" : "\"";
    WrappersFile << "#include " << Prefix << IncludedFile << Suffix << "\n";
  }

  for (const std::string &Definition : FunctionWrappers)
    WrappersFile << Definition << '\n';

  for (const std::string &Instantiation : ClassTemplateInstantiations)
    WrappersFile << Instantiation;
  for (const std::string &Instantiation : FunctionTemplateInstantiations)
    WrappersFile << Instantiation;
}

#endif